name: MDVAspectos
version: '1.0.1'
main: com.mdvcraft.mdvaspectos.MDVAspectosPlugin
api-version: '1.21'
author: MDVCRAFT
depend: [PlaceholderAPI, SkinsRestorer]
commands:
  aspecto:
    description: Abre el menu de aspectos de tu raza.
    usage: /aspecto
    aliases: [aspectos]
permissions:
  mdvaspectos.use:
    description: Permite abrir el menu de aspectos.
    default: true
  mdvaspectos.reload:
    description: Permite recargar MDVAspectos.
    default: op
