name: MDVAspectos
version: '1.1.5'
main: com.mdvcraft.mdvaspectos.MDVAspectosPlugin
api-version: '1.21'
author: MDVCRAFT
depend: [PlaceholderAPI, SkinsRestorer]
commands:
  aspecto:
    description: Abre el menu de aspectos de tu raza.
    usage: /aspecto
    aliases: [aspectos]
permissions:
  mdvaspectos.use:
    description: Permite abrir el menu de aspectos.
    default: true
  mdvaspectos.reload:
    description: Permite recargar MDVAspectos.
    default: op
  mdvaspectos.skinmemory.free:
    description: Permite que MDVAspectos recuerde skins libres usadas con /skin.
    default: op

  mdvcraft.race.selected:
    description: Marca que el jugador ya eligio raza y puede usar comandos normales.
    default: false
  mdvcraft.racegate.bypass:
    description: Permite saltarse el bloqueo global de comandos por raza.
    default: op
